# Generated by Django 3.2.3 on 2021-05-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=60)),
                ('modalidade', models.CharField(choices=[('RF', 'Renda fixa'), ('RV', 'Renda variável'), ('CP', 'Criptomoeda')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('D', 'Deletado')], max_length=1)),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
    ]
