# Generated by Django 3.2.3 on 2021-05-19 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiInvest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('D', 'Desativado')], max_length=1)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiInvest.conta')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimentos',
            },
        ),
        migrations.CreateModel(
            name='tipo_transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('D', 'Desativado')], max_length=1)),
                ('fk_transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiInvest.transacao')),
            ],
            options={
                'verbose_name': 'Tipo Movimento',
                'verbose_name_plural': 'Tipos de Movimentos',
            },
        ),
        migrations.CreateModel(
            name='taxa_transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('D', 'Desativado')], max_length=1)),
                ('fk_tipo_transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiInvest.tipo_transacao')),
            ],
            options={
                'verbose_name': 'Tipo Movimento',
                'verbose_name_plural': 'Tipos de Movimentos',
            },
        ),
    ]
