# Generated by Django 3.2.3 on 2021-05-20 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiInvest', '0003_auto_20210519_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxa_transacao',
            options={'verbose_name': 'Taxa de transação', 'verbose_name_plural': 'Taxas de Transações'},
        ),
        migrations.AlterModelOptions(
            name='tipo_transacao',
            options={'verbose_name': 'Tipo transação', 'verbose_name_plural': 'Tipos de Transações'},
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
    ]
